[
$DOCTYPE:"shell_script";
$shell_script:
$shell_script href="https://github.com/Tulee2425/TuleesCustomBuild/edit/%E2%96%A1%E2%96%A0/%E2%96%A1%E2%96%A0.sh";
{
$script_type:````["data()"]````=["symbols_text()"],
$data_type:````["□■_txt(text_Font)"]````=["symbols.txt(□■_txt)"],
$function_SET:````["get_ATTRIBUTE(A_Z)"]````=["UPPERCASE(□_■)"],
$replace_TEXT:````["STRING(UPPERCASE)"]````=["VAR_CHAR(□_■)"],
$content_IMPORT:````["■.sh"]````=["IMPORT(get_ATTRIBUTE)"],
$object_EXPORT:````["■.sh"]````=["EXPORT(ATTRIBUTE)"],
$function_set:````["get_attribute(a_z)"]````=["lowercase(□_□)"],
$replace_text:````["string(lowercase)"]````=["var_char(□_□)"],
$content_import:````["□.sh"]````=["import(get_attribute)"],
$object_export:````["□.sh"]````=["export(attribute)"],
$new_value:````["lowercase(□)"]````=["alpha(replace)"],
$VAR_CHAR:````["lowercase(□)"]````=["get_attribute()"],
$NEW_VALUE:````["UPPERCASE(■)"]````=["get_ATTRIBUTE()"],
$VAR_CHAR:````["UPPERCASE(■)"]````=["get_ATTRIBUTE()"],
$□=["no_index()"],
$■=["NO_INDEX()"];
}

    {
    $function_set:"VAR_CHAR"="get_attribute()";
      $FOR:"alpha(□)"="attribute()",
      $IF:"function_set"="get_attribute",
      $ELSE:"content()"="null";
    $function_SET:"VAR_CHAR"="get_ATTRIBUTE()";
      $FOR:"ALPHA(■)"="ATTRIBUTE()",
      $IF:"function_SET"="get_ATTRIBUTE"
      $ELSE:"CONTENT()"="NULL";
     }
         {
         $VAR_CHAR:"alpha(a)=Attribute(□)",
         $VAR_CHAR:"ALPHA(A)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(b)=Attribute(□)",
         $VAR_CHAR:"ALPHA(B)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(c)=Attribute(□)",
         $VAR_CHAR:"ALPHA(C)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(d)=Attribute(□)",
         $VAR_CHAR:"ALPHA(D)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(e)=Attribute(□)",
         $VAR_CHAR:"ALPHA(E)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(f)=Attribute(□)",
         $VAR_CHAR:"ALPHA(F)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(g)=Attribute(□)",
         $VAR_CHAR:"ALPHA(G)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(h)=Attribute(□)",
         $VAR_CHAR:"ALPHA(H)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(i)=Attribute(□)",
         $VAR_CHAR:"ALPHA(I)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(j)=Attribute(□)",
         $VAR_CHAR:"ALPHA(J)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(k)=Attribute(□)",
         $VAR_CHAR:"ALPHA(K)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(l)=Attribute(□)",
         $VAR_CHAR:"ALPHA(L)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(m)=Attribute(□)",
         $VAR_CHAR:"ALPHA(M)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(n)=Attribute(□)",
         $VAR_CHAR:"ALPHA(N)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(o)=Attribute(□)",
         $VAR_CHAR:"ALPHA(O)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(p)=Attribute(□)",
         $VAR_CHAR:"ALPHA(P)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(q)=Attribute(□)",
         $VAR_CHAR:"ALPHA(Q)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(r)=Attribute(□)",
         $VAR_CHAR:"ALPHA(R)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(s)=Attribute(□)",
         $VAR_CHAR:"ALPHA(S)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(t)=Attribute(□)",
         $VAR_CHAR:"ALPHA(T)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(u)=Attribute(□)",
         $VAR_CHAR:"ALPHA(U)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(v)=Attribute(□)",
         $VAR_CHAR:"ALPHA(V)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(w)=Attribute(□)",
         $VAR_CHAR:"ALPHA(W)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(x)=Attribute(□)",
         $VAR_CHAR:"ALPHA(X)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(y)=Attribute(□)",
         $VAR_CHAR:"ALPHA(Y)=ATTRIBUTE(■)",
         $VAR_CHAR:"alpha(z)=Attribute(□)",
         $VAR_CHAR:"ALPHA(Z)=ATTRIBUTE(■)";
         }
]
